import os

BASE = "/Users/lucienmount/Arch_App_V2/architecture-app/docs/docs2"

def write(rel_path: str, content: str) -> None:
    full_path = os.path.join(BASE, rel_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"✔ Wrote {rel_path}")

# ---------------- 1) PAST WALKS / JINK SUMMARY / NOLLI MAP ----------------
WALK_MAP = (
    "# Past Walk Page & Jink Summary (Nolli Map)\n\n"
    "## Summary\n"
    "A single screen combining personal history and visual memory.\n"
    "Users see their past walks and a black-and-white Nolli-style city map that reveals only the regions they’ve explored.\n"
    "It’s the visual embodiment of \"what you’ve seen.\"\n\n"
    "## Layout Hierarchy\n"
    "1. Past Walks Page\n"
    "   - Carousel of walks (most recent first).\n"
    "   - Each tile shows the generated drawing + duration + XP earned.\n"
    "   - Tap -> opens Jink Summary Screen for that walk.\n\n"
    "2. Jink Summary Screen\n"
    "   - Header: Walk name, date, XP gained.\n"
    "   - Body: list of visited buildings (cards with photos and blurbs).\n"
    "   - Footer: \"View on Map\" -> opens the Nolli-style city view.\n\n"
    "3. Nolli Map View\n"
    "   - 2D black-and-white rendering of the city (vector or raster).\n"
    "   - Only visited buildings are visible:\n"
    "     - Each is surrounded by a feathered circle (soft mask radius ~75 m).\n"
    "     - Connection lines join the sequence of buildings in that walk.\n"
    "   - Unexplored areas are dimmed under a haze overlay.\n"
    "   - As the user explores more buildings, the map gradually clears, mimicking exploration in EU4-style fog-of-war.\n\n"
    "## Data Inputs\n"
    "- passport_entries table for visited buildings.\n"
    "- Building coords -> projected to map coordinates.\n"
    "- User city center from last derive session.\n"
    "- Optional cached map tiles or vector basemap.\n\n"
    "## Rendering Logic\n"
    "1) Preload map tile layer in grayscale (desaturated).\n"
    "2) For each visited building:\n"
    "   - draw feathered radial gradient mask at its position.\n"
    "   - opacity = min(1.0, visit_count / 3).\n"
    "3) Connect consecutive visits from the same walk with semi-transparent line.\n"
    "4) Overlay subtle fog mask on unvisited areas (alpha 0.65).\n"
    "5) When zooming:\n"
    "   - Reveal more detail, fade-in building outlines.\n"
    "   - At highest zoom, show names; at lowest, only clusters.\n\n"
    "## Interactions\n"
    "| Gesture | Action |\n"
    "|--------|--------|\n"
    "| Tap building | Opens building info card (same as scan result) |\n"
    "| Pinch | Zoom in/out (fog dynamically recalculated) |\n"
    "| Swipe left/right | Switch between walks |\n"
    "| Long press | \"Revisit walk\" CTA -> triggers derive route from current location |\n\n"
    "## Performance\n"
    "- Use off-screen canvas / WebGL layer for mask compositing.\n"
    "- Tile cache (256 px) with fog alpha baked.\n"
    "- p95 render target: <= 30 ms per frame on mid device.\n\n"
    "## Orb Integration\n"
    "- When the map opens, orb glows faintly at map center.\n"
    "- As user hovers over a building or zooms near it, orb pulses with that building’s archetype hue (from its style vector).\n"
    "- When a new area is revealed for the first time, orb emits a small outward ripple and user earns +5 XP \"Explorer bonus.\"\n\n"
    "## Aesthetic Reference\n"
    "- Base palette: white background, black fill for mass, light gray streets.\n"
    "- Feather masks: radial falloff, multiply blend.\n"
    "- Haze overlay: low-contrast bluish tint, animated noise (slow drift).\n\n"
    "## Future Hooks\n"
    "- Toggle between \"All walks\" (aggregate map) and single walk path.\n"
    "- Option to export current map view as image for sharing.\n"
)

# ---------------- 2) PRO XP MILESTONES (CREATIVE UNLOCKS) ----------------
PRO_MILESTONES = (
    "# XP Milestones for Pro Users (Creative Unlocks)\n\n"
    "## Purpose\n"
    "Pro users should feel tangible creative growth as they gain XP.\n"
    "These unlocks reward exploration and contribution without adding grind or competition.\n\n"
    "## Philosophy\n"
    "- Keep it useful, not gamey.\n"
    "- Each milestone should extend capability, not vanity.\n"
    "- Milestones are tied to total XP, not time or subscription age.\n\n"
    "## Unlock Table\n"
    "| Total XP | Unlock | Description |\n"
    "|----------|--------|-------------|\n"
    "| 1 000 | Deep Dive Credits x1 | Access detailed AI building reports. Earn +1 per additional 1000 XP. |\n"
    "| 2 500 | Custom Derives | Create and save personalized routes; share privately. |\n"
    "| 5 000 | Stamp Designer | Compose personal stamp styles (color + icon). |\n"
    "| 7 500 | Public Derives | Publish routes for others; visible after staff review. |\n"
    "| 10 000 | Aesthetic Export | Export your profile vector as visual (orb state, color palette). |\n"
    "| 15 000 | Orb Modulation | Orb gains reactive shader layer reflecting your top archetype blend in real time. |\n\n"
    "## Integration with Entitlements\n"
    "Each unlock toggles a boolean or counter inside entitlements:\n\n"
    "{\n"
    "  \"deep_dive_credits\": 3,\n"
    "  \"custom_derives\": true,\n"
    "  \"stamp_designer\": true,\n"
    "  \"public_derives\": false,\n"
    "  \"aesthetic_export\": false,\n"
    "  \"orb_modulation\": true\n"
    "}\n\n"
    "Edge function /xp/update checks for crossing thresholds and appends new entitlements.\n"
    "Client shows a small toast: \"Unlocked: Custom Derives.\"\n\n"
    "## Visual Feedback\n"
    "- Unlock events pulse the orb in gold for 1 s.\n"
    "- Newly unlocked actions get a shimmering outline for 24 h.\n\n"
    "## Safeguards\n"
    "- Prevent spam by debouncing entitlement recalculations.\n"
    "- XP rollbacks never remove unlocks already granted.\n"
    "- Upgrades sync on next login if user was offline.\n\n"
    "## Future Extension\n"
    "- Allow Pro users to trade unused Deep Dive credits for \"guest passes.\"\n"
    "- Add subtle orb tint per milestone tier for visual bragging rights.\n"
)

if __name__ == "__main__":
    write("frontend/walk_summary_and_citymap.md", WALK_MAP)
    write("systems/xp_system/milestone_unlocks.md", PRO_MILESTONES)
    print("✅ Added Past Walk / Nolli Map and Pro XP Milestones docs to docs2/")
